### ISSUE TITLE
Stuck on beta 1

### ISSUE THREAD

**Issue by SyarifAuliaR** [pierr3/TrackAudio#191]
Hello, 

i have an issue with track audio. in detailed, i can't get the latest version running on my PC with a windows 11 OS. i've tried to install beta 2 and the same result happened. as my last effort i tried to install the beta 1 and it's working like a charm without any issues. The issues i had with beta 2 and 3 is that the application won't event run and just crashed without any windows opening. i've tried to do a clean uninstall including deleting the log folder ( Appdata/local/trackaudio) and the one in roaming folder (Appdata/roaming/trackaudio) and try to re-install the beta 2 and 3 but it doesn't help

**Comment by pierr3** [comment]
Please have a look in the Readme at the section titled "Ports and endpoints access required for TrackAudio"

The silent crash has been fixed in the sense that you will get a pop up explaining what is happening.

What is most likely is happening is that your firewall or other network restriction is preventing TrackAudio to access https://raw.githubusercontent.com

Please have a look and see if you can access that endpoint in your browser

**Comment by SyarifAuliaR** [comment]
thank you for the reply, i have checked all the endpoints and i can access all of the required endpoints also ensuring the needed port is open. i've also double check my firewall settings and antivirus to make sure no connection is blocked for trackaudio but it still give me the same result. the application can't launched properly even if i tried to open it from CMD

**Comment by pierr3** [comment]
Alright, thanks for checking, it must be something else. Keep using beta 1
for now and the next beta is likely to fix your issue, as the startup code
has been tweaked.

**Comment by SyarifAuliaR** [comment]
thanks for the update, sadly i've tried it and it didn't solve the problem, the beta 3 and beta 2 still not running at all on my device...

**Comment by pierr3** [comment]
Please try beta 4, also have a look at the readme, namely ensure that the version check URL is not blocked by a firewall either on your system or by your ISP. You can click here to see if it works: [https://raw.githubusercontent.com/pierr3/TrackAudio/refs/heads/main/MANDATORY_VERSION](https://raw.githubusercontent.com/pierr3/TrackAudio/refs/heads/main/MANDATORY_VERSION)

**Comment by pierr3** [comment]
@mjpikat are you on beta 4 and have you tried the fixes above? It does seem to be linked to failed version check.

**Comment by mjpikat** [comment]
> @mjpikat are you on beta 4 and have you tried the fixes above? It does seem to be linked to failed version check.

Yup, however the link you mentioned above works for me.

**Comment by pierr3** [comment]
@mjpikat @SyarifAuliaR could you both try the build in #240 and let me know if that fixes it?

**Comment by mjpikat** [comment]
> @mjpikat @SyarifAuliaR could you both try the build in #240 and let me know if that fixes it?

It does! Now running for me :)

**Comment by SyarifAuliaR** [comment]
> @mjpikat @SyarifAuliaR could you both try the build in #240 and let me know if that fixes it?

It does solve the issue, thank you so much and sorry for the late response.. have been busy lately

**Comment by pierr3** [comment]
That's great, i'll push the update soon.

**Comment by mjpikat** [comment]
Latest update to 1.3.3 brings back the same problem
